#+OPTIONS:   H:4 num:nil toc:nil author:nil timestamp:nil tex:t 
#+BEGIN_HTML
---
layout: page
title: Tutorial 6
comments: true
---
#+END_HTML
-----

/This page can be commented/

* Problem 1
/Show that the solution obtained by the Method of Separation of Variables to the PDE:/

\begin{align}
\label{eq:pde1}
u_x = t u_t
\end{align}
/is of the form/ $u(x,t)=K e^{\lambda x}t^\lambda$, /where/ $K$ /and/ $\lambda$ /are constants./

*Proof*: Assume that $u(x,t)$ can be written as 
\begin{align}
\label{eq:u1}
u(x,t) = F(x)G(t).
\end{align}

Then $u_x$ and $u_t$ are given by
\begin{align}
\label{eq:u1a}
u_x = F'(x) G(t),\,u_t = F(x)G'(t).
\end{align}

Replacing $u_x$ and $u_t$ in the original equation \eqref{eq:pde1}, we have

\begin{align}
\label{eq:pde1a}
F'(x) G(t) = t F(x) G'(t).
\end{align}

In order to separate the variables, we want to move all the $x$ terms to one side of the equation and all the $t$ terms to the other side, which leads to

\begin{align}
\label{eq:pde1b}
\frac{F'(x)}{F(x)} = \frac{tG'(t)}{G(t)}.
\end{align}

We now successfully separate the variables $x$ and $t$. We will conclude that the Left-Hand Side (LHS) and the Right-Hand Side (RHS) of \eqref{eq:pde1b} must be a constant $\lambda$, i.e.,
\begin{align}
\label{eq:pde1c}
\frac{F'(x)}{F(x)} =\lambda, \,\frac{tG'(t)}{G(t)}=\lambda,
\end{align}
which gives us two ODEs.

To solve the ODE, we will use the fact that
\begin{align}
\label{eq:chainrule}
\frac{d \log y}{dx} = \frac{d\log y}{dy}\times \frac{dy}{dx} = \frac{1}{y} \times y' = \frac{y'}{y}.
\end{align}

For the first ODE, we will take the integral over $x$ on both hand side of the equation:
\begin{align}
\label{eq:ode1}
\log(F(x))=\int{\frac{F'(x)}{F(x)} dx} = \int{\lambda dx} = \lambda x + C_1,
\end{align}
where $C_1$ is some constant. Therefore,
\begin{align}
\label{eq:ode1a}
F(x) = \exp\left(\lambda x + C_1\right) = \exp(C_1) \exp(\lambda x) = A_1 \exp(\lambda x),
\end{align}
where $A_1 = \exp(C_1)$ is another constant.

For the second ODE, we will rewrite it a little bit in order to use \eqref{eq:chainrule}: 
\begin{align}
\label{eq:ode2}
\frac{tG'(t)}{G(t)}=\lambda \Rightarrow \frac{G'(t)}{G(t)}=\frac{\lambda}{t}.
\end{align}
Take the integral over $t$ on both side of the equation:
\begin{align}
\label{eq:ode2a}
\log(G(t)) = \int \frac{G'(t)}{G(t)} dt=\int \frac{\lambda}{t} dt = \lambda\log t+C_2,
\end{align}
which implies that
\begin{align}
\label{eq:ode2b}
G(t) = \exp(\lambda \log t + C_2) = \exp(C_2) \left[\exp(\log t)\right]^\lambda = A_2 t^\lambda,
\end{align}
where $A_2 = \exp (C_2)$ is another constant.

Now we have solved $F(x)$ and $G(t)$, we can put \eqref{eq:ode1a} and \eqref{eq:ode2b} back to \eqref{eq:u1} to get
\begin{align}
\label{eq:u1b}
u(x,t) = F(x)G(t) = K \exp(\lambda x) t^\lambda.
\end{align}
* Problem 2
/Solve/ 
\begin{align}
\label{eq:pde2}
u_t = 2 u_{xx}, \, x\in(0,3), \,t\in (0,\infty),
\end{align}
 /with initial conditions:/
\begin{align}
u(0,t)& = 0 \label{eq:init2a}\\
u(3,t)& = 0 \label{eq:init2b}\\
u(x,0)& = 5\sin(4\pi x) -3\sin(8\pi x) +2\sin(10\pi x)\label{eq:init2c}\\
|u(x,t)|& < M \text{ for all }x\in(0,3),\,t\in(0,\infty)\label{eq:init2d}
\end{align}

*Solution*: Assume that $u$ can be written as
\begin{align}
\label{eq:u2}
u(x,t) = F(x)G(t).
\end{align}
As a result,
\begin{align}
\label{eq:u2a}
u_t = F(x)G'(t),\,u_{xx}=F''(x)G(t).
\end{align}
Substituting \eqref{eq:u2a} into \eqref{eq:pde2}, we get
\begin{align}
\label{eq:pde2a}
F(x)G'(t) = 2F''(x) G(t)\Rightarrow \frac{G'(t)}{2G(t)}=\frac{F''(x)}{F(x)} = \mu,
\end{align}
where $\mu is some constant.

For the first ODE, we will use the same techniques as in \eqref{eq:ode1} and \eqref{eq:ode1a} to get
\begin{align}
\label{eq:ode21}
G(t) = C_1 \exp(2\mu t).
\end{align}

Now if $\mu$ is positive, $\exp(2\mu t)\rightarrow\infty$ when $t\rightarrow \infty$. However, from the initial condition \eqref{eq:init2d}, $u(x,t)$ must be bounded. As a result, $\mu\leq 0$ must be non-positive. 

Let us define
\begin{align}
\label{eq:lambdadef}
\lambda = \sqrt{-\mu}.
\end{align}

For the second ODE, we have
\begin{align}
\label{eq:ode22}
F''(x) -\mu F(x) = F''(x) + \lambda^2 F(x) = 0.
\end{align}
This is a second-order homogeneous ODE with constant coefficient. The general solution[fn:1] of this ODE is
\begin{align}
\label{eq:ode22a}
F(x) = A_1\cos(\lambda x) + A_2 \sin(\lambda x).
\end{align}

Now using the initial condition \eqref{eq:init2a}, we have
\begin{align}
\label{eq:ode22b}
0 = u(0,t) = F(0) G(t) = (A_1 \cos 0 + A_2 \sin 0) G(t) = A_1 G(t).
\end{align}
Therefore, $A_1$ must be $0$ and $F(x) = A_2 \sin (\lambda x)$.

By the initial condition \eqref{eq:init2b}
\begin{align}
\label{eq:ode22c}
0 = u(3,t) = F(3)G(t) = A_2 \sin (3\lambda) G(t).
\end{align}
Therefore, $sin(3\lambda) = 0$, which implies that
\begin{align}
\label{eq:lambda}
3\lambda = n\pi\Rightarrow\lambda = n\pi /3.
\end{align}

Combining \eqref{eq:lambda}, \eqref{eq:ode22a}, \eqref{eq:ode21}, we know that
\begin{align}
\label{eq:u2b}
u(x,t) = B_n \sin \left(\frac{n\pi}{3}x\right)\exp\left(-\frac{2\pi^2}{9}n^2 t\right),
\end{align}
where $B_n = C_1A_2$ is a constant.

Now we want use the final initial condition \eqref{eq:init2c}. However, you will find that if $u$ is given by \eqref{eq:u2b}, then $u$ cannot satisfy \eqref{eq:init2c}. To solve this problem, we observe that the original PDE is linear. This will imply that the sum of two solutions to \eqref{eq:pde2} is also a solution. Therefore, the following $u$ is also a solution to the PDE:
\begin{align}
\label{eq:u2c}
u(x,t) = \sum_{n=0}^\infty B_n \sin \left(\frac{n\pi}{3}x\right)\exp\left(-\frac{2\pi^2}{9}n^2 t\right).
\end{align}

By the initial condition \eqref{eq:init2c},
\begin{align}
\label{eq:u2d}
u(x,0)&= 5\sin(4\pi x) -3\sin(8\pi x) +2\sin(10\pi x) \\
&= \sum_{n=0}^\infty B_n \sin \left(\frac{n\pi}{3}x\right).\nonumber
\end{align}
Therefore, we have
\begin{align}
\label{eq:u2e}
B_{12}=5,\,B_{24}=-3,\,B_{30}=2,\,B_n = 0 \text{ otherwise}.
\end{align}

Combining \eqref{eq:u2c} and \eqref{eq:u2e}, we get
\begin{align}
u(x,t)&= 5\sin(4\pi x)\exp(-32\pi^2t) -3\sin(8\pi x)\exp(-128\pi^2t)\nonumber \\
&+2\sin(10\pi x) \exp(-200\pi^2t)
\end{align}
* Problem 3
/Using Laplace Transform, solve the following wave equation/
\begin{align}
\label{eq:pde3}
u_{tt} = u_{xx},\,x\in(0,1),\,t\in(0,\infty),
\end{align}
subject to the boundary conditions
\begin{align}
u(0,t) &= 0,\label{eq:init3a}\\
u(1,t) &= 0,\label{eq:init3b}\\
\end{align}
and the initial conditions
\begin{align}
u(x,0)&=0,\label{eq:init3c}\\
u_t(x,0)&=\sin(\pi x)\label{eq:init3d}.
\end{align}

*Solution[fn:2]:* Notice that there are two variables: $x$ and $t$. The PDE is invariant, so we can take the Laplace transform w.r.t. either $x$ or $t$. Here we will take the transform w.r.t. $t$. Define
\begin{align}
\label{eq:u3}
U(x,s) = \int_0^\infty u(x,t)\exp(-st)dt.
\end{align}


* Problem 4
[fn:1] You can check find an introduction on this type of ODE [[https://en.wikipedia.org/wiki/Linear_differential_equation#Homogeneous_equations_with_constant_coefficients][here]].
[fn:2] You can use direct integral method for Problem 4 in Tutorial 5 to conclude that the solution of the PDE must be of the form $u(x,t) = F(t-x) + G(t+x)$, where $F$ and $G$ are arbitrary functions.
