#+OPTIONS:   H:4 num:nil toc:nil author:nil timestamp:nil tex:t 
#+BEGIN_HTML
---
layout: page
title: Tutorial 6
comments: true
---
#+END_HTML
-----

/You can provide comments at the end of this page if you find some proofs confusing. Alternatively, you can also annotate the page by selecting the text and write down your questions (it might not on smart phones). I will try to answer them asap./

* Problem 1
/Show that the solution obtained by the Method of Separation of Variables to the PDE:/

\begin{align}
\label{eq:pde1}
u_x = t u_t
\end{align}
/is of the form/ $u(x,t)=K e^{\lambda x}t^\lambda$, /where/ $K$ /and/ $\lambda$ /are constants./

*Proof*: Assume that $u(x,t)$ can be written as 
\begin{align}
\label{eq:u1}
u(x,t) = F(x)G(t).
\end{align}

Then $u_x$ and $u_t$ are given by
\begin{align}
\label{eq:u1a}
u_x = F'(x) G(t),\,u_t = F(x)G'(t).
\end{align}

Replacing $u_x$ and $u_t$ in the original equation \eqref{eq:pde1}, we have

\begin{align}
\label{eq:pde1a}
F'(x) G(t) = t F(x) G'(t).
\end{align}

In order to separate the variables, we want to move all the $x$ terms to one side of the equation and all the $t$ terms to the other side, which leads to

\begin{align}
\label{eq:pde1b}
\frac{F'(x)}{F(x)} = \frac{tG'(t)}{G(t)}.
\end{align}

We now successfully separate the variables $x$ and $t$. We will conclude that the Left-Hand Side (LHS) and the Right-Hand Side (RHS) of \eqref{eq:pde1b} must be a constant $\lambda$, i.e.,
\begin{align}
\label{eq:pde1c}
\frac{F'(x)}{F(x)} =\lambda, \,\frac{tG'(t)}{G(t)}=\lambda,
\end{align}
which gives us two ODEs.

To solve the ODE, we will use the fact that
\begin{align}
\label{eq:chainrule}
\frac{d \log y}{dx} = \frac{d\log y}{dy}\times \frac{dy}{dx} = \frac{1}{y} \times y' = \frac{y'}{y}.
\end{align}

For the first ODE, we will take the integral over $x$ on both hand side of the equation:
\begin{align}
\label{eq:ode1}
\log(F(x))=\int{\frac{F'(x)}{F(x)} dx} = \int{\lambda dx} = \lambda x + C_1,
\end{align}
where $C_1$ is some constant. Therefore,
\begin{align}
\label{eq:ode1a}
F(x) = \exp\left(\lambda x + C_1\right) = \exp(C_1) \exp(\lambda x) = A_1 \exp(\lambda x),
\end{align}
where $A_1 = \exp(C_1)$ is another constant.

For the second ODE, we will rewrite it a little bit in order to use \eqref{eq:chainrule}: 
\begin{align}
\label{eq:ode2}
\frac{tG'(t)}{G(t)}=\lambda \Rightarrow \frac{G'(t)}{G(t)}=\frac{\lambda}{t}.
\end{align}
Take the integral over $t$ on both side of the equation:
\begin{align}
\label{eq:ode2a}
\log(G(t)) = \int \frac{G'(t)}{G(t)} dt=\int \frac{\lambda}{t} dt = \lambda\log t+C_2,
\end{align}
which implies that
\begin{align}
\label{eq:ode2b}
G(t) = \exp(\lambda \log t + C_2) = \exp(C_2) \left[\exp(\log t)\right]^\lambda = A_2 t^\lambda,
\end{align}
where $A_2 = \exp (C_2)$ is another constant.

Now we have solved $F(x)$ and $G(t)$, we can put \eqref{eq:ode1a} and \eqref{eq:ode2b} back to \eqref{eq:u1} to get
\begin{align}
\label{eq:u1b}
u(x,t) = F(x)G(t) = K \exp(\lambda x) t^\lambda.
\end{align}
* Problem 2
/Solve/ 
\begin{align}
\label{eq:pde2}
u_t = 2 u_{xx}, \, x\in(0,3), \,t\in (0,\infty),
\end{align}
 /with boundary and initial conditions:/
\begin{align}
u(0,t)& = 0 \label{eq:init2a}\\
u(3,t)& = 0 \label{eq:init2b}\\
u(x,0)& = 5\sin(4\pi x) -3\sin(8\pi x) +2\sin(10\pi x)\label{eq:init2c}\\
|u(x,t)|& < M \text{ for all }x\in(0,3),\,t\in(0,\infty)\label{eq:init2d}
\end{align}

** Separation of Variables
Assume that $u$ can be written as
\begin{align}
\label{eq:u2}
u(x,t) = F(x)G(t).
\end{align}
As a result,
\begin{align}
\label{eq:u2a}
u_t = F(x)G'(t),\,u_{xx}=F''(x)G(t).
\end{align}
Substituting \eqref{eq:u2a} into \eqref{eq:pde2}, we get
\begin{align}
\label{eq:pde2a}
F(x)G'(t) = 2F''(x) G(t)\Rightarrow \frac{G'(t)}{2G(t)}=\frac{F''(x)}{F(x)} = \mu,
\end{align}
where $\mu$ is some constant.

For the first ODE, we will use the same techniques as in \eqref{eq:ode1} and \eqref{eq:ode1a} to get
\begin{align}
\label{eq:ode21}
G(t) = C_1 \exp(2\mu t).
\end{align}

For the second ODE, we have
\begin{align}
\label{eq:ode22}
F''(x) -\mu F(x) = 0.
\end{align}

Let us define
\begin{align}
\label{eq:lambdadef}
\lambda \triangleq \sqrt{|\mu|}.
\end{align}


Equation \eqref{eq:ode22} is a second-order homogeneous ODE with constant coefficient. The general solution[fn:1] of this ODE is
\begin{align}
\label{eq:ode22a}
F(x) = \begin{cases}
A_1\cos(\lambda x) + A_2 \sin(\lambda x)& \mu < 0\\
A_1\exp(\lambda x) + A_2 \exp(-\lambda x)& \mu > 0\\
A_1 + A_2  x& \mu = 0\\
\end{cases}
\end{align}

Substituting $F(x)$ and $G(t)$ in \eqref{eq:u2}, we have
\begin{align}
\label{eq:u2general}
u(x,t) = \begin{cases}
\left[B\cos(\lambda x) + D \sin(\lambda x)\right]\exp(2\mu t)& \mu < 0\\
\left[B\exp(\lambda x) + D \exp(-\lambda x)\right]\exp(2\mu t)& \mu > 0\\
B + D  x& \mu = 0\\
\end{cases}
\end{align}
where $B=A_1C_1$ and $D = A_2C_1$ are constants.
** Incorporating the Boundary and Initial Conditions
*** Case 1: $\mu > 0$
   If $\mu$ is positive, $\exp(2\mu t)\rightarrow\infty$ when $t\rightarrow \infty$. However, from the initial condition \eqref{eq:init2d}, $u(x,t)$ must be bounded. As a result, $B = D = 0$ when $\mu > 0$.

*** Case 2: $\mu = 0$
Using the boundary condition \eqref{eq:init2a} and \eqref{eq:init2b}, we have
\begin{align}
0 &= u(0,t) = B + D \times 0, \\
0 &=u(3,t) = B + D\times 3.
\end{align}
which implies that $B = D = 0$.

*** Case 3: $\mu < 0$
Using the initial condition \eqref{eq:init2a}, we have
\begin{align}
\label{eq:ode22b}
0 = u(0,t) = F(0) G(t) = (B \cos 0 + D \sin 0) G(t) = B G(t).
\end{align}
Therefore, $B$ must be $0$ and $F(x) = D \sin (\lambda x)$.

By the initial condition \eqref{eq:init2b}
\begin{align}
\label{eq:ode22c}
0 = u(3,t) = F(3)G(t) = D \sin (3\lambda) G(t).
\end{align}
Therefore, $\sin(3\lambda) = 0$, which implies that
\begin{align}
\label{eq:lambda}
3\lambda = n\pi\Rightarrow\lambda = n\pi /3.
\end{align}

Combining \eqref{eq:lambda}, \eqref{eq:ode22a}, \eqref{eq:ode21}, we know that
\begin{align}
\label{eq:u2b}
u(x,t) = D_n \sin \left(\frac{n\pi}{3}x\right)\exp\left(-\frac{2\pi^2}{9}n^2 t\right).
\end{align}

Now we want use the initial condition \eqref{eq:init2c}. However, you will find that if $u$ is given by \eqref{eq:u2b}, then $u$ cannot satisfy \eqref{eq:init2c}. To solve this problem, we observe that the original PDE is linear. This will imply that the sum of any number of solutions to \eqref{eq:pde2} is also a solution. Therefore, the following $u$ is also a solution to the PDE:
\begin{align}
\label{eq:u2c}
u(x,t) = \sum_{n=1}^\infty D_n \sin \left(\frac{n\pi}{3}x\right)\exp\left(-\frac{2\pi^2}{9}n^2 t\right).
\end{align}

By the initial condition \eqref{eq:init2c},
\begin{align}
\label{eq:u2d}
u(x,0)&= 5\sin(4\pi x) -3\sin(8\pi x) +2\sin(10\pi x) \\
&= \sum_{n=1}^\infty D_n \sin \left(\frac{n\pi}{3}x\right).\nonumber
\end{align}
Therefore, we have
\begin{align}
\label{eq:u2e}
D_{12}=5,\,D_{24}=-3,\,D_{30}=2,\,D_n = 0 \text{ otherwise}.
\end{align}

Combining \eqref{eq:u2c} and \eqref{eq:u2e}, we get
\begin{align}
u(x,t)&= 5\sin(4\pi x)\exp(-32\pi^2t) -3\sin(8\pi x)\exp(-128\pi^2t)\nonumber \\
&+2\sin(10\pi x) \exp(-200\pi^2t)
\end{align}
* Problem 3
/Using Laplace Transform, solve the following wave equation/
\begin{align}
\label{eq:pde3}
u_{tt} = u_{xx},\,x\in(0,1),\,t\in(0,\infty),
\end{align}
subject to the boundary conditions
\begin{align}
u(0,t) &= 0,\label{eq:init3a}\\
u(1,t) &= 0,\label{eq:init3b}\\
\end{align}
and the initial conditions
\begin{align}
u(x,0)&=0,\label{eq:init3c}\\
u_t(x,0)&=\sin(\pi x)\label{eq:init3d}.
\end{align}

*Solution[fn:2]:* Notice that there are two variables: $x$ and $t$. The PDE is invariant, so we can take the Laplace transform w.r.t. either $x$ or $t$. Here we will take the transform w.r.t. $t$. Define
\begin{align}
\label{eq:u3}
U(x,s) = \int_0^\infty u(x,t)\exp(-st)dt.
\end{align}

Since we take the transform w.r.t. $t$, we have
\begin{align}
\label{eq:laplace3utt}
\int_0^\infty u_{tt}(x,t)\exp(-st)dt &= s^2 U(x,s)-su(x,0)-u_t(x,0)\\
&=s^2 U(x,s)-s\times 0-\sin(\pi x),\\
\label{eq:laplace3uxx}
\int_0^\infty u_{xx}(x,t)\exp(-st)dt &=  U_{xx}(x,s).
\end{align}
Equation \eqref{eq:laplace3utt} is due to the derivative properties of Laplace transform.

Now substituting $u_{tt}$ and $u_{xx}$ in \eqref{eq:pde3}, we will get
\begin{align}
\label{eq:pde3a}
s^2 U(x,s)-\sin(\pi x) = U_{xx}(x,s).
\end{align}

The above equation is a PDE. However, since we only take the derivative w.r.t. $x$, we can view $s$ as a constant and solve the equation as an ODE. 

*** Solving the ODE \eqref{eq:pde3a}
We will rewrite \eqref{eq:pde3a} as
\begin{align}
\label{eq:pde3b}
U_{xx} - s^2 U = -\sin(\pi x).
\end{align}
The above equation is a constant coefficients *nonhomogeneous* ODE. The corresponding *homogeneous* equation is
\begin{align}
\label{eq:pde3homo}
U_{xx} - s^2 U = 0,
\end{align}
the solution of which is
\begin{align}
\label{eq:pde3homosoln}
U = A_1 \exp(sx) + A_2 \exp(-sx),
\end{align}
where $A_1$ and $A_2$ are some constants.

Now we just need to find *one* solution for the *nonhomogeneous* ODE. Let us guess the solution[fn:3] is 
\begin{align}
\label{eq:pde3particularsolution}
U = k_1 \cos(\pi x) + k_2 \sin (\pi x).
\end{align}
Substituting $U_{xx}$ and $U$ in \eqref{eq:pde3b}, we get
\begin{align}
\label{eq:pde3nonhomo}
k_1(-\pi^2-s^2)\cos(\pi x) +k_2(-\pi^2-s^2)\sin(\pi x) =- \sin(\pi x).
\end{align}
Therefore, $k_1 = 0$, $k_2 = 1/(s^2+\pi^2)$ and *one* solution of \eqref{eq:pde3b} is
\begin{align}
\label{eq:pde3soln}
U = \frac{1}{s^2+\pi^2}\sin(\pi x).
\end{align}
Thus, *All* the solution of \eqref{eq:pde3b} will equal to the particular solution \eqref{eq:pde3soln} plus the general solution for the homogenous equation \eqref{eq:pde3homosoln}, i.e.,
\begin{align}
\label{eq:pde3allsolution}
U = \frac{1}{s^2+\pi^2}\sin(\pi x) + A_1 \exp(sx) + A_2 \exp(-sx).
\end{align}

*** Incorporating the boundary conditions.

We will now use the boundary conditions to determine $A_1$ and $A_2$. /(We have already used all the initial conditions when we perform the Laplace transform.)/

\begin{align}
u(0,t) = 0&\Rightarrow U(0,s)=\int_{0}^\infty u(0,t)\exp(-st)dt = 0,\\
u(1,t) = 0&\Rightarrow U(1,s)=\int_{0}^\infty u(1,t)\exp(-st)dt = 0.\\
\end{align}

On the other hand, by \eqref{eq:pde3allsolution}, we have
\begin{align}
0&= U(0,s)= 0 + A_1 + A_2,\\
0&= U(1,s)= 0 + A_1\exp(s) + A_2\exp(-s).\\
\end{align}
This implies that $A_1$ and $A_2 = 0$. Therefore, by incorporating the boundary conditions, we know $U$ is given by
\begin{align}
\label{eq:pde3solna}
U(x,s) = \frac{1}{s^2+\pi^2}\sin(\pi x).
\end{align}

*** Inverse Laplace Transform
We now need to do an inverse Laplace transform to get $u(x,t)$. *Notice that we can now view $x$ as a constant*.

\begin{align}
\label{eq:inverselt3}
u(x,t)&=\mathcal L^{-1}\left\{\frac{1}{s^2+\pi^2}\sin(\pi x)\right\} \\
&= \pi^{-1}\sin(\pi x)\mathcal L^{-1}\left\{\frac{\pi}{s^2+\pi^2}\right\} = \pi^{-1}\sin(\pi x)\sin(\pi t).\nonumber
\end{align}
/The last inequality is from the Laplace Transform Table./
* Problem 4
/The PDE given by/
\begin{align}
\label{eq:pde4}
y_x - x^2y_t = 0,
\end{align}
/with initial and boundary conditions given by/
\begin{align}
y(x,0)&=0, \label{eq:init4a}\\
y(0,t)&=H(t), \label{eq:init4b}\\
\end{align}
/where $H(t)$ is the unit step function./

1. /Solve $y(x,t)$ using Laplace Transform/
2. /Why does it not help to apply Laplace transform to solve/
\[
ty_x - x y_t = 0.
\]

*Solution*: Notice that the PDE \eqref{eq:pde4} is *only invariant in* $t$, we need to take the Laplace transform w.r.t. $t$.

Define
\begin{align}
\label{eq:lt4}
Y(x,s) = \int_0^\infty y(x,t)\exp(-st)dt.
\end{align}

As a result
\begin{align}
\label{eq:lt4a}
\int_0^\infty y_x(x,t)\exp(-st)dt &= Y_x(x,s)\\
\int_0^\infty x^2y_t(x,t)\exp(-st)dt &= x^2\left[sY(x,s)-y(x,0)\right]=x^2sY(x,s)
\end{align}

Hence, we can take the Laplace transform on both sides of \eqref{eq:pde4} and rewrite it as
\begin{align}
\label{eq:ode4}
Y_x - x^2 s Y = 0\Rightarrow \frac{Y_x}{Y} =x^2s.
\end{align}

We can view $s$ as a constant and solve the above equation as an ODE. Use \eqref{eq:chainrule}, we take the integral over $x$ on both sides of the equation and get
\begin{align}
\label{eq:ode4a}
\int \frac{Y_x}{Y}dx =\int x^2s dx\Rightarrow \log(Y) = \frac{1}{3}x^3s+C\Rightarrow Y = A \exp\left(\frac{1}{3}x^3s\right),
\end{align}
where $C$ and $A=\exp(C)$ are some constants.

We now use the boundary condition \eqref{eq:init4b} and get
\begin{align}
\label{eq:boundary4}
Y(0,s) = \int_0^\infty H(t) \exp(-st)dt = \frac{1}{s}.\\
\end{align}

On the other hand, from \eqref{eq:ode4a}, $Y(0,s) = A$, which implies that $A = 1/s$ and
\begin{align}
\label{eq:ode4b}
Y(x,s) = \frac{1}{s}\exp\left(\frac{1}{3}x^3s\right).
\end{align}

Now we know that 
\[
\mathcal L\left\{H(t)\right\} = \frac{1}{s},
\]

So using the time shift properties of Laplace Transform, we can conclude that
\[
y(x,t) = H\left(t+\frac{1}{3}x^3\right).
\]
 
For the PDE $ty_x - xy_t = 0$, it is neither invariant w.r.t. $t$ nor invariant w.r.t. $x$. Hence, we *cannot* use Laplace transform to solve it since we need to take the Laplace Transform w.r.t. an invariant variable.

[fn:1] You can check find an introduction on this type of ODE [[https://en.wikipedia.org/wiki/Linear_differential_equation#Homogeneous_equations_with_constant_coefficients][here]].
[fn:2] You can use direct integral method for Problem 4 in Tutorial 5 to conclude that the solution of the PDE must be of the form $u(x,t) = F(t-x) + G(t+x)$, where $F$ and $G$ are arbitrary functions.
[fn:3] In general, if we have a nonhomogeneous ODE like this
\[y^{(n)}+\alpha_1 y^{(n-1)}+\cdots+\alpha_{n-1}y'+\alpha_n y = \exp(\lambda x), \]
we should guess a particular solution is of the form $y = k\exp(\lambda x)$, where $k$ is a constant.
